# Source: https://pspdfkit.com/blog/2018/how-to-run-your-phoenix-application-with-docker/

# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    image: ukasiu/pokedex
    environment:
      # Variable to connect to our Postgres server
      #             scheme    ://username:password@host:port/database
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pokedex
      # Variables for entrypoint.sh
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: pokedex
      PGPASSWORD: postgres
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    volumes:
      # Mapping for live reload
      - ".:/app"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:10.1
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      # Mapping the port to make Postgres accessible outside of the container
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
